"""numbers/harness.py — Tenenbaum NUMBER-GAME port of the lambda instrument,
answering the single-task-family objection.

Adapted (imports/paths/packaging only) from the pre-registered
``frontier_lab/echo_numgame.py``. Numeric logic unchanged; the hypothesis space,
priors, and exact learners are imported from ``lambda_lattice.references``.

Same measurement logic as the reasoning harness (generation lambda, thinking
toggle, ""|meet|sizep instruction branches, sanity/parse gates, per-trial exact
references) on Tenenbaum's (2000) number game over [1,100]:

  demos  n positive examples of a hidden numeric category, generated by one of
         10 demo rules (multiples/last-digit/primes), each with a designated
         BROADER superset rule in H
  probes stratified to separate rule membership from numeric proximity:
    in_far      in narrow rule, held out, >=8 away from every possible demo
    off_near    demo+-1, outside both rules
    broad_only  in the broad rule only, >=3 from every demo
    out_far     outside both rules, >=8 from every demo (both accounts: reject)
    repeat      demo re-membership sanity (must accept)

  lambda := acceptance on off_near + broad_only (generalization beyond the
  narrowest consistent rule). Bayes reference contracts lambda(n) -> 0;
  a similarity/proximity learner keeps it flat.

Env knobs: SAME ETH_* names as the reasoning harness.
  ETH_MODELS, ETH_SEEDS, ETH_SEED0, ETH_ARMS, ETH_FMT (ng1), ETH_MAXNEW,
  ETH_MAXLEN, ETH_BACKEND vllm|hf|mock, ETH_BATCH, ETH_OUT
  (default echo_numgame.json), ETH_NDEMOS_B, ETH_INSTRUCT ""|meet|sizep

No-GPU power check (mock oracles must be recovered by the stats), via CLI:
  ETH_BACKEND=mock ETH_MODELS=bayes:none,prox:none ETH_SEEDS=36 \
  ETH_OUT=echo_numgame_mockcheck.json python -m lambda_lattice.numbers.harness
or via the python API:
  numbers.harness.run({"models": "bayes:none,prox:none", "backend": "mock",
                       "seeds": 36, "out": "..."} )
"""
from __future__ import annotations

import json
import math
import os
import pathlib
import random
import re
import time

from ..references import (
    ERLANG_SIGMA, HSPACE, NMAX, PROX_SCALE, RULE_SHARE, RULES_EXT,
    bayes_predict, prox_predict,
)

HERE = pathlib.Path(__file__).resolve().parent


def _results_base() -> pathlib.Path:
    from .._paths import results_dir
    return results_dir()


OUT = _results_base() / os.environ.get("ETH_OUT", "echo_numgame.json")

MODELS = os.environ.get("ETH_MODELS", "Qwen/Qwen3-0.6B:on").split(",")
SEEDS = int(os.environ.get("ETH_SEEDS", "12"))
SEED0 = int(os.environ.get("ETH_SEED0", "0"))
ARMS = os.environ.get("ETH_ARMS", "a,b").split(",")
FMT = os.environ.get("ETH_FMT", "ng1")
MAXNEW = int(os.environ.get("ETH_MAXNEW", "2048"))
MAXLEN = int(os.environ.get("ETH_MAXLEN", "8192"))
BACKEND = os.environ.get("ETH_BACKEND", "vllm")
BATCH = int(os.environ.get("ETH_BATCH", "8"))
NDEMOS_B = [int(x) for x in
            os.environ.get("ETH_NDEMOS_B", "1,2,4,8,16,32").split(",")]
INSTRUCT = os.environ.get("ETH_INSTRUCT", "")  # ""|meet|sizep
TEMP, TOP_P = 0.6, 0.95

LABELS = ("wug", "dax")  # counterbalanced per seed, as in the Boolean harness
GAP_IN = 8   # min distance from any in_far probe to any possible demo
GAP_OUT = 8  # min distance from any out_far probe to every sampled demo
GAP_BROAD = 3


# ---------------------------------------------------------------------------
# demo rules: (name, designated broad superset rule in H, 4 held-out in_far
# probes). Demo pool = rule members <= min(probes) - GAP_IN (primes: 2 also
# dropped so demos stay inside the broad rule 'odd').
# ---------------------------------------------------------------------------
DEMO_RULES = [
    ("mult8", "mult4", (72, 80, 88, 96)),
    ("mult6", "mult3", (78, 84, 90, 96)),
    ("mult9", "mult3", (72, 81, 90, 99)),
    ("mult4", "even", (88, 92, 96, 100)),
    ("end0", "mult5", (70, 80, 90, 100)),
    ("end5", "mult5", (65, 75, 85, 95)),
    ("end3", "odd", (63, 73, 83, 93)),
    ("end7", "odd", (67, 77, 87, 97)),
    ("end4", "even", (64, 74, 84, 94)),
    ("primes", "odd", (79, 83, 89, 97)),
]


def demo_pool(rname: str, probe_in) -> list[int]:
    members = sorted(RULES_EXT[rname])
    pool = [m for m in members if m <= min(probe_in) - GAP_IN]
    if rname == "primes":
        pool = [m for m in pool if m != 2]
    return pool


for _r, _b, _p in DEMO_RULES:  # design invariants
    # probes are held-out members of the narrow rule; the demo POOL (not the
    # whole rule: primes includes 2, odd doesn't) must lie inside the broad
    # rule so 'broad' is always a consistent broader hypothesis
    assert set(_p) <= RULES_EXT[_r]
    assert set(demo_pool(_r, _p)) <= RULES_EXT[_b]
    assert len(demo_pool(_r, _p)) >= 4 and len(_p) == 4


def make_ng_trial(nd: int, seed: int, big: bool):
    """One trial: demos (nested across nd for paired slopes) + stratified
    probes. Returns (demos, probes[(value, kind)], rule_name)."""
    ridx = seed % len(DEMO_RULES)
    rname, bname, probe_in_all = DEMO_RULES[ridx]
    rule, broad = RULES_EXT[rname], RULES_EXT[bname]
    pool = demo_pool(rname, probe_in_all)
    # demo rng independent of nd -> demo multisets nested across the n-sweep
    drng = random.Random(50_000 + 1_000_000 * ridx + seed)
    order = pool[:]
    drng.shuffle(order)
    if nd <= len(order):
        demos = order[:nd]
    else:  # repetition when nd exceeds distinct pool, like the Boolean harness
        demos = order + [drng.choice(pool) for _ in range(nd - len(order))]
    demos = demos[:]
    drng.shuffle(demos)
    dset = set(demos)

    # probe rng independent of nd where possible (in_far identical across n)
    prng = random.Random(70_000 + 1_000_000 * ridx + seed)
    q = 4 if big else 2
    in_far = list(probe_in_all) if big else prng.sample(probe_in_all, 2)
    off_cand = sorted({d + e for d in dset for e in (-1, 1)}
                      - rule - broad - dset)
    off_cand = [x for x in off_cand if 1 <= x <= NMAX]
    off_near = prng.sample(off_cand, min(q, len(off_cand)))
    broad_cand = [x for x in sorted(broad - rule)
                  if min(abs(x - d) for d in dset) >= GAP_BROAD]
    broad_only = prng.sample(broad_cand, min(q, len(broad_cand)))
    out_cand = [x for x in range(1, NMAX + 1)
                if x not in rule and x not in broad
                and min(abs(x - d) for d in dset) >= GAP_OUT]
    n_out = 4 if big else 1
    out_far = prng.sample(out_cand, min(n_out, len(out_cand)))
    repeats = prng.sample(sorted(dset), min(2 if big else 1, len(dset)))

    probes = ([(v, "in_far") for v in in_far]
              + [(v, "off_near") for v in off_near]
              + [(v, "broad_only") for v in broad_only]
              + [(v, "out_far") for v in out_far]
              + [(v, "repeat") for v in repeats])
    return demos, probes, rname


# ---------------------------------------------------------------------------
# prompts (mirror the reasoning harness wording, numbers instead of items)
# ---------------------------------------------------------------------------
def demo_block(demos, pos, neg):
    lines = [f"Every number below belongs to the same hidden category of "
             f"numbers between 1 and 100. Numbers in the category are labeled "
             f"'{pos}'; numbers outside it are labeled '{neg}'."]
    for d in demos:
        lines.append(f"Number: {d} -> {pos}")
    return "\n".join(lines)


def probe_prompt(block, probe, pos, neg):
    if INSTRUCT == "sizep":
        return (f"{block}\n\nNumber: {probe}\n"
                f"First list every rule that is consistent with ALL the "
                f"labeled numbers above. Then apply the size principle: every "
                f"additional labeled number that is consistent with a narrow "
                f"rule makes it a suspicious coincidence unless that narrow "
                f"rule is the true one — so the MORE labeled numbers you have "
                f"seen, the more strongly you should trust only the narrowest "
                f"consistent rule and reject numbers outside it; with only a "
                f"FEW numbers, broader consistent rules remain plausible and "
                f"you should be more permissive. Count the labeled numbers "
                f"above and weigh this explicitly. Then answer '{pos}' ONLY "
                f"IF this number is accepted under that reasoning; otherwise "
                f"answer '{neg}'. End your reply with exactly 'Answer: {pos}' "
                f"or 'Answer: {neg}'.")
    if INSTRUCT == "meet":
        return (f"{block}\n\nNumber: {probe}\n"
                f"First list every rule that is consistent with ALL the "
                f"labeled numbers above. Then answer '{pos}' ONLY IF this "
                f"number satisfies EVERY one of those rules; otherwise answer "
                f"'{neg}'. End your reply with exactly 'Answer: {pos}' or "
                f"'Answer: {neg}'.")
    return (f"{block}\n\nNumber: {probe}\n"
            f"Decide the label of this number. End your reply with exactly "
            f"'Answer: {pos}' or 'Answer: {neg}'.")


def strip_think(text: str) -> tuple[str, int]:
    """Return (final segment, think chars). Handles Qwen3 <think>, R1, gpt-oss."""
    if "</think>" in text:
        head, _, tail = text.rpartition("</think>")
        return tail, len(head)
    if "assistantfinal" in text:
        head, _, tail = text.rpartition("assistantfinal")
        return tail, len(head)
    if "<|channel|>final<|message|>" in text:
        head, _, tail = text.rpartition("<|channel|>final<|message|>")
        return tail, len(head)
    return text, 0


def parse_label(final_seg: str, pos: str, neg: str):
    """Prefer last 'Answer: X'; fallback last occurrence of either label."""
    m = list(re.finditer(rf"answer\s*[:\-]?\s*\**\s*({pos}|{neg})",
                         final_seg.lower()))
    if m:
        return int(m[-1].group(1) == pos)
    hits = [(mm.start(), lab) for lab in (pos, neg)
            for mm in re.finditer(re.escape(lab), final_seg.lower())]
    if not hits:
        return None
    return int(max(hits)[1] == pos)


# ---------------------------------------------------------------------------
# backends (copied from the reasoning harness, not imported: keeps mock mode
# free of transformers and the validated instrument untouched)
# ---------------------------------------------------------------------------
def render_chat(tok, user_msg: str, mode: str) -> str:
    kw = {}
    if mode in ("on", "off"):
        kw["enable_thinking"] = mode == "on"
    elif mode in ("high", "low"):
        kw["reasoning_effort"] = mode
    return tok.apply_chat_template(
        [{"role": "user", "content": user_msg}],
        tokenize=False, add_generation_prompt=True, **kw)


class VllmBackend:
    def __init__(self, name: str):
        from transformers import AutoTokenizer
        from vllm import LLM

        self.tok = AutoTokenizer.from_pretrained(name)
        self.llm = LLM(model=name, dtype="bfloat16", max_model_len=MAXLEN,
                       gpu_memory_utilization=0.92, enforce_eager=False)

    def generate(self, user_msgs, seeds, mode):
        from vllm import SamplingParams

        prompts = [render_chat(self.tok, m, mode) for m in user_msgs]
        params = [SamplingParams(temperature=TEMP, top_p=TOP_P,
                                 max_tokens=MAXNEW, seed=s) for s in seeds]
        outs = self.llm.generate(prompts, params)
        res = []
        for o in outs:
            c = o.outputs[0]
            res.append((c.text, c.finish_reason == "length"))
        return res


class HfBackend:
    def __init__(self, name: str):
        import torch
        from transformers import AutoModelForCausalLM, AutoTokenizer

        self.torch = torch
        self.tok = AutoTokenizer.from_pretrained(name)
        if self.tok.pad_token is None:
            self.tok.pad_token = self.tok.eos_token
        self.tok.padding_side = "left"
        self.model = AutoModelForCausalLM.from_pretrained(
            name, dtype=torch.bfloat16, device_map="auto").eval()

    def generate(self, user_msgs, seeds, mode):
        res = []
        for i in range(0, len(user_msgs), BATCH):
            chunk = [render_chat(self.tok, m, mode)
                     for m in user_msgs[i:i + BATCH]]
            self.torch.manual_seed(seeds[i])
            enc = self.tok(chunk, return_tensors="pt", padding=True,
                           add_special_tokens=False).to(self.model.device)
            with self.torch.no_grad():
                out = self.model.generate(
                    **enc, max_new_tokens=MAXNEW, do_sample=True,
                    temperature=TEMP, top_p=TOP_P,
                    pad_token_id=self.tok.pad_token_id)
            n_in = enc["input_ids"].shape[1]
            for row in out:
                text = self.tok.decode(row[n_in:], skip_special_tokens=True)
                res.append((text, len(row) - n_in >= MAXNEW))
        return res


class MockBackend:
    """Instrument power check (no GPU): 'bayes' = sampling oracle from the
    exact size-principle predictive; 'prox' = sampling oracle from numeric
    proximity (scale 6, deliberately != the reference's 10 to show the stats
    are robust to scale mismatch). Both re-parse demos/probe from the PROMPT
    TEXT, so the check also covers prompt readability end to end."""

    def __init__(self, name: str):
        assert name in ("bayes", "prox"), name
        self.kind = name

    def generate(self, user_msgs, seeds, mode):
        res = []
        for msg, sd in zip(user_msgs, seeds):
            lab = re.search(r"labeled\s+'(\w+)'; numbers outside it are "
                            r"labeled\s+'(\w+)'", msg)
            pos, neg = lab.group(1), lab.group(2)
            demos = [int(x) for x in
                     re.findall(rf"Number: (\d+) -> {pos}\b", msg)]
            probe = int(re.findall(r"Number: (\d+)", msg)[-1])
            if self.kind == "bayes":
                p = bayes_predict(demos, [probe])[probe]
            else:
                p = math.exp(-min(abs(probe - d) for d in demos) / 6.0)
            acc = random.Random(sd).random() < p
            res.append((f"Answer: {pos if acc else neg}", False))
        return res


# ---------------------------------------------------------------------------
# one condition = one (model, mode)
# ---------------------------------------------------------------------------
def trial_cells():
    rng = range(SEED0, SEED0 + SEEDS)
    cells = []
    if "a" in ARMS:
        cells += [("a", 8, s) for s in rng]
    if "b" in ARMS:
        cells += [("b", nd, s) for nd in NDEMOS_B for s in rng]
    return cells


DISC_KINDS = ("in_far", "off_near", "broad_only", "out_far")
LAM_KINDS = ("off_near", "broad_only")


def run_condition(be, name: str, mode: str) -> dict:
    cells = trial_cells()
    prompts, seeds, meta = [], [], []
    trials = {}
    for arm, nd, seed in cells:
        pos, neg = LABELS if seed % 2 == 0 else (LABELS[1], LABELS[0])
        demos, probes, rname = make_ng_trial(nd, seed, big=(arm == "a"))
        bay = bayes_predict(demos, [v for v, _ in probes])
        block = demo_block(demos, pos, neg)
        key = (arm, nd, seed)
        trials[key] = {"pos": pos, "neg": neg, "demos": demos, "rule": rname,
                       "probes": probes, "bayes": bay, "rows": []}
        for idx, (val, kind) in enumerate(probes):
            prompts.append(probe_prompt(block, val, pos, neg))
            seeds.append(3_000_000 + (0 if arm == "a" else 1_000_000)
                         + nd * 4_000 + seed * 100 + idx)
            meta.append((key, idx, kind))

    print(f"[{name}:{mode}] {len(prompts)} prompts ...", flush=True)
    t0 = time.time()
    outs = be.generate(prompts, seeds, mode)
    gen_s = time.time() - t0
    print(f"[{name}:{mode}] generation done in {gen_s:.0f}s", flush=True)

    thinks = mode in ("on", "native", "high", "low")
    traces = []
    for (key, idx, kind), (text, truncated) in zip(meta, outs):
        tr = trials[key]
        final_seg, think_chars = strip_think(text)
        if truncated and thinks and think_chars == 0:
            ans = None
        elif truncated and not final_seg.strip():
            ans = None
        else:
            ans = parse_label(final_seg, tr["pos"], tr["neg"])
        val = tr["probes"][idx][0]
        tr["rows"].append({"kind": kind, "val": val, "ans": ans,
                           "bayes": tr["bayes"][val],
                           "prox": prox_predict(tr["demos"], val),
                           "think_chars": think_chars, "trunc": int(truncated)})
        if len(traces) < 20 and kind in LAM_KINDS:
            traces.append({"key": str(key), "kind": kind, "val": val,
                           "think": text[:2000], "final": final_seg[:300]})

    trial_rows = []
    for (arm, nd, seed), tr in trials.items():
        rows = tr["rows"]

        def rate(kinds, answered=True):
            v = [r["ans"] for r in rows if r["kind"] in kinds
                 and r["ans"] is not None]
            return sum(v) / len(v) if v else float("nan")

        def ref(field, kinds):
            v = [r[field] for r in rows if r["kind"] in kinds]
            return sum(v) / len(v) if v else float("nan")

        rep = [r["ans"] for r in rows if r["kind"] == "repeat"
               and r["ans"] is not None]
        outp = [r["ans"] for r in rows if r["kind"] == "out_far"
                and r["ans"] is not None]
        sanity = ((sum(rep) + sum(1 - a for a in outp))
                  / max(len(rep) + len(outp), 1))
        n_ans = sum(1 for r in rows if r["ans"] is not None)
        disc = [r for r in rows if r["kind"] in DISC_KINDS
                and r["ans"] is not None]
        fit_b = (sum(1 - abs(r["ans"] - r["bayes"]) for r in disc)
                 / len(disc)) if disc else float("nan")
        fit_p = (sum(1 - abs(r["ans"] - r["prox"]) for r in disc)
                 / len(disc)) if disc else float("nan")
        trial_rows.append({
            "arm": arm, "n": nd, "seed": seed, "rule": tr["rule"],
            "lambda": rate(LAM_KINDS),
            "lambda_in": rate(("in_far",)),
            "lambda_off": rate(("off_near",)),
            "lambda_broad": rate(("broad_only",)),
            "out_acc": rate(("out_far",)),
            "sanity": sanity, "parse_rate": n_ans / len(rows),
            "trunc_rate": sum(r["trunc"] for r in rows) / len(rows),
            "think_chars": sum(r["think_chars"] for r in rows) / len(rows),
            "bayes": ref("bayes", LAM_KINDS),        # scorer-compat: ref on λ
            "bayes_in": ref("bayes", ("in_far",)),
            "bayes_off": ref("bayes", ("off_near",)),
            "bayes_broad": ref("bayes", ("broad_only",)),
            "bayes_out": ref("bayes", ("out_far",)),
            "prox": ref("prox", LAM_KINDS),
            "prox_in": ref("prox", ("in_far",)),
            "fit_bayes": fit_b, "fit_prox": fit_p,
            "detail": [(r["kind"], r["val"], r["ans"],
                        round(r["bayes"], 4), round(r["prox"], 4))
                       for r in rows]})
    return {"mode": mode, "fmt": FMT, "gen_s": round(gen_s, 1),
            "sampling": {"temp": TEMP, "top_p": TOP_P, "max_new": MAXNEW},
            "instruct": INSTRUCT, "trials": trial_rows, "traces": traces}


def summarize(cond: dict):
    tr = [t for t in cond["trials"] if t["sanity"] >= 0.75
          and t["parse_rate"] >= 0.8]
    out = {"n_learned": len(tr), "n_total": len(cond["trials"])}

    def m(ts, k):
        v = [t[k] for t in ts if t[k] == t[k]]
        return round(sum(v) / len(v), 3) if v else None

    a = [t for t in tr if t["arm"] == "a"]
    if a:
        for k in ("lambda", "lambda_in", "lambda_off", "lambda_broad",
                  "out_acc", "fit_bayes", "fit_prox", "bayes", "bayes_in",
                  "prox", "prox_in"):
            out[f"armA_{k}"] = m(a, k)
        if out["armA_fit_bayes"] is not None and out["armA_fit_prox"] is not None:
            out["armA_delta_fit"] = round(
                out["armA_fit_bayes"] - out["armA_fit_prox"], 3)
    for nd in NDEMOS_B:
        b = [t for t in tr if t["arm"] == "b" and t["n"] == nd]
        if b:
            out[f"armB_lambda_n{nd}"] = m(b, "lambda")
            out[f"armB_in_n{nd}"] = m(b, "lambda_in")
            out[f"armB_bayes_n{nd}"] = m(b, "bayes")
            out[f"armB_prox_n{nd}"] = m(b, "prox")
    # paired slope lambda(nmax)-lambda(nmin), and the Bayes reference slope
    lo, hi = NDEMOS_B[0], NDEMOS_B[-1]
    for field, label in (("lambda", "slope"), ("bayes", "bayes_slope"),
                         ("lambda_in", "slope_in")):
        d_lo = {t["seed"]: t[field] for t in tr
                if t["arm"] == "b" and t["n"] == lo and t[field] == t[field]}
        d_hi = {t["seed"]: t[field] for t in tr
                if t["arm"] == "b" and t["n"] == hi and t[field] == t[field]}
        common = sorted(set(d_lo) & set(d_hi))
        if len(common) >= 2:
            d = [d_hi[s] - d_lo[s] for s in common]
            mu = sum(d) / len(d)
            var = sum((x - mu) ** 2 for x in d) / (len(d) - 1)
            se = (var / len(d)) ** 0.5
            out[f"armB_{label}"] = round(mu, 3)
            out[f"armB_{label}_se"] = round(se, 3)
            out[f"armB_{label}_z"] = round(mu / max(se, 1e-9), 2)
    out["mean_think_chars"] = round(
        sum(t["think_chars"] for t in cond["trials"])
        / max(len(cond["trials"]), 1), 1)
    return out


def _run_all() -> dict:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    all_res = {}
    if OUT.exists():
        try:
            all_res = json.loads(OUT.read_text(encoding="utf-8"))
        except Exception:
            all_res = {}
    by_model: dict[str, list[str]] = {}
    for spec in MODELS:
        name, _, mode = spec.rpartition(":")
        if not name:
            name, mode = spec, "none"
        by_model.setdefault(name, []).append(mode)
    for name, modes in by_model.items():
        be = (MockBackend if BACKEND == "mock"
              else VllmBackend if BACKEND == "vllm" else HfBackend)(name)
        for mode in modes:
            cond_key = f"{name}:{mode}"
            print(f"==== {cond_key} ====", flush=True)
            cond = run_condition(be, name, mode)
            cond["summary"] = summarize(cond)
            all_res[cond_key] = cond
            all_res["_meta"] = {"seeds": SEEDS, "seed0": SEED0, "arms": ARMS,
                                "fmt": FMT, "ndemos_b": NDEMOS_B,
                                "backend": BACKEND, "instruct": INSTRUCT,
                                "task": "numgame",
                                "rule_share": RULE_SHARE,
                                "erlang_sigma": ERLANG_SIGMA,
                                "prox_scale": PROX_SCALE}
            OUT.write_text(json.dumps(all_res), encoding="utf-8")
            print(json.dumps(cond["summary"], indent=1), flush=True)
            print(f"wrote {OUT}", flush=True)
        del be
    return all_res


def _as_list(v):
    return v if isinstance(v, list) else str(v).split(",")


def run(config: dict | None = None) -> dict:
    """Python API entry point. Config keys mirror the ETH_* env vars without the
    prefix (lowercase): models, seeds, seed0, arms, fmt, maxnew, maxlen, backend,
    batch, ndemos_b, instruct, out. Returns the merged results dict (written to
    disk). Set backend="mock" with models="bayes:none,prox:none" for the no-GPU
    power check."""
    config = config or {}
    global MODELS, SEEDS, SEED0, ARMS, FMT, MAXNEW, MAXLEN, BACKEND, BATCH
    global NDEMOS_B, INSTRUCT, OUT
    if "models" in config:
        MODELS = _as_list(config["models"])
    if "seeds" in config:
        SEEDS = int(config["seeds"])
    if "seed0" in config:
        SEED0 = int(config["seed0"])
    if "arms" in config:
        ARMS = _as_list(config["arms"])
    if "fmt" in config:
        FMT = str(config["fmt"])
    if "maxnew" in config:
        MAXNEW = int(config["maxnew"])
    if "maxlen" in config:
        MAXLEN = int(config["maxlen"])
    if "backend" in config:
        BACKEND = str(config["backend"])
    if "batch" in config:
        BATCH = int(config["batch"])
    if "ndemos_b" in config:
        NDEMOS_B = [int(x) for x in _as_list(config["ndemos_b"])]
    if "instruct" in config:
        INSTRUCT = str(config["instruct"])
    if "out" in config:
        OUT = pathlib.Path(config["out"])
    return _run_all()


def main():
    _run_all()


if __name__ == "__main__":
    main()
